BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        id: clear_string
        text: 'Clear'
        font_size: 48
        on_press: app.handle_clear()
    TextInput:
        id: input_name
        text: ''
        font_size: 48
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
        font_size: 48
    Label:
        id: output_label
        text: 'Enter your name'
        color: (1,1,0,1)
        font_size: 48